### ISSUE TITLE
Parallax plugin causing issues when body has a background image

### ISSUE THREAD

**Issue by c0sm1n87** [puikinsh/shapely#110]
https://github.com/puikinsh/shapely/issues/49#issuecomment-267277959

**Comment by ezraholm50** [comment]
You're the best!

> Well the issue is that its not overlapping but there's blank space between the widgets that is showing the site wide background.
> 
> ![deepinscreenshot20161215102051](https://cloud.githubusercontent.com/assets/13510720/21218303/51d6289a-c2b0-11e6-9d1b-f72c984e25a1.png)
> 
> Any idea when the update will be pushed to the wordpress theme repo's?
> Thank you!
> 
> Edit: I've been told by @FreeWPTP that my theme was having this issue. Therefore my post.

**Comment by ezraholm50** [comment]
after adding this css code:
```
body .parallax-mirror:nth-child(2) {
visibility: hidden !important;
}
```

It looks like this:
![deepinscreenshot20161215122100](https://cloud.githubusercontent.com/assets/13510720/21222185/f71160e4-c2c0-11e6-8d76-e8499fbc3627.png)

![deepinscreenshot20161215122042](https://cloud.githubusercontent.com/assets/13510720/21222195/08652a38-c2c1-11e6-887a-c42b729a9ede.png)

Note that below the client/partner widget there is a small bar of about 1 px shining through, above client/partner and below the "Ons verhaal" parralax widget a bar of about 4 px.

Also above the "Ons verhaal" parralax widget there is a dark 1px line, if you look closely.

Thanks again!

**Comment by ezraholm50** [comment]
And its back to the original bug, think had something to to with the caching.

**Comment by ezraholm50** [comment]
@c0sm1n87 I hope you are doing well. Is there anything I can do to help out or test? Hope you have great days coming days!

**Comment by c0sm1n87** [comment]
hello @ezraholm50, the problem is in the parallax plugin. unfortunately, i`ve been busy implementing these changes: 

https://github.com/puikinsh/shapely/issues/112
https://github.com/puikinsh/shapely/issues/111
https://github.com/puikinsh/shapely/issues/113

and didn`t have time to fix this

**Comment by ezraholm50** [comment]
No problem, I'll patiently wait for it! If I can do anything to help you with any of those issue's just let me know. I can provide domains, host stuff for you, anything. Thanks for your help! Enjoy these days!

**Comment by c0sm1n87** [comment]
hello @ezraholm50 

i've taken another look on your website, and as far as I can see the body background image is not needed. The image from the header is set from the parallax widget here:

    <div class="parallax-window fullscreen" data-parallax="scroll" data-image-src="https://www.promotionbikes.nl/wp-content/uploads/2016/11/misty_amsterdam-wallpaper-1920x1080-e1479294708994.jpg">

Removing it from the customizer options should fix your problem

**Comment by ezraholm50** [comment]
@c0sm1n87 Best wishes for the new year to you!

Well as far as I know its the theme background thats needed. Not the widgets one, because the navigation bar is blank. It would look off if only the parralax background is set, get me?

Removing the widget messes up the CSS as it is right now alignments etc. Right now someone gave me some css code to remove or hide the image without deleting the widget (cant remove only the image, no option for that) so that sucks...

Also I tried what you suggested, removed the widget and made a new one without the background image. But... still a small bar exists after clearing all caches...

Any suggestions?

**Comment by cristianraiber** [comment]
This seems to be a limitation of the JS parallax plugin used. I'm afraid there's nothing we can do about it at this point. We'll try updating the 3rd party JS library bundled with the theme that handles the parallax sections. Hopefully, that'll fix the issue for you.

**Comment by ezraholm50** [comment]
That is just to bad. How would I be able to verify the update works? What do I update?

**Comment by ezraholm50** [comment]
Well it actually made it a little better but still is there. Is there anything I could try to reinstall or anything? Since not everyone has this problem?

![promo1](https://cloud.githubusercontent.com/assets/13510720/22707500/43115fe4-ed73-11e6-82a6-bc19e3fad77b.png)
![promo2](https://cloud.githubusercontent.com/assets/13510720/22707501/4312d586-ed73-11e6-9e2c-cae6f251dc88.png)
