### ISSUE TITLE
Show blog summary option

### ISSUE THREAD

**Issue by Sandmxn** [puikinsh/shapely#200]
I've recently updated to the latest and greatest Shapely version(June/July 2017) and I'm pretty sure there was an option so that you could select in customise>theme options>blog settings to set it so it shows the summary of a blog post. At the moment my website is using the small-grid.php layout and it is showing the whole text of each article.

**Comment by cristianraiber** [comment]
@c0sm1n87 - please see this.

**Comment by c0sm1n87** [comment]
@Sandmxn 

I am searching through older versions of Shapely and I can't find any option for displaying the excerpt of the post instead of the actual content.

These is one of the oldest version of the customizer.php file ( which holds the options ) and I can`t find it.

https://github.com/puikinsh/shapely/blob/16554b965af1d09e9c02c880a4f6b727ecdd6156/inc/customizer.php

I suggest adding "read more" tags in your posts.

**Comment by Sandmxn** [comment]
@c0sm1n87 

Maybe i'm just going a bit crazy and imagined it being there. 
I've also added the read more tags for now.

Thanks for checking anyway. You may as well close this.
