### ISSUE TITLE
Theme update failed

### ISSUE THREAD

**Issue by simonschllng** [puikinsh/shapely#214]
Today I updated from `1.0.2` to `1.1.6` what completely destroyed my front page. So I rolled back from backup and did the update-process step-by-step, version-by-version.
I found the following:

- With `1.0.6`, the front page widgets were gone
- `1.1.0` plus the plugin brought them back
- `1.1.2` removed my static (widget) front page and started to display the empty page "Home"
- Somewhere on the way, theme settings like custom css were lost.

Someone with similar experiences or a solution? I would like to get to the latest version without loosing all my settings.

**Comment by cristianraiber** [comment]
@giucu91 - please see this.

**Comment by giucu91** [comment]
Hello @simonschllng,

We made some changes to Shapely in order to make it in accordance with WordPress.org Guidelines.
The changes are : 
- We moved the widgets from the theme to the Shapely Companion plugin because we are not allowed with widgets in the theme
- In order to have the homepage with our widgets you will need to create a page that uses the "Home Page" template and then set it up in Settings -> Reading as Front Page.

Regarding the custom CSS, I'll investigate to see what happens there. If you are aware of other settings that you lost in the process please tell me which.

**Comment by simonschllng** [comment]
Thanks, fixed the homepage thing. CSS was the only setting that was los in the end. Copy/paste from backup was a quick fix.

**Comment by cristianraiber** [comment]
Closing this as it seems to be fixed.
