### ISSUE TITLE
Tagline doesn't appear

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#227]
How can I make the tagline appear? I already put it in “Site Identity” and ticked “Display Site Title and Tagline” However it doesn’t show. 

Reported here: https://colorlib.com/wp/forums/topic/tagline-doesnt-appear/#post-124864

**Comment by cristianraiber** [comment]
@giucu91 - can you please look into this?

**Comment by cristianraiber** [comment]
So we could basically say this was a design decision @laranz. From what it looks, we don't have a foolproof way of handling this, especially for backwards compatibility. I'm talking about the users that would have to suffer most from this.

**Comment by laranz** [comment]
@cristianraiber Agreed, no problem!

@giucu91 by default the site title alone display, what I am trying is just add the tagline along with it, just like this https://colorlib.com/wp/forums/topic/tagline-doesnt-appear/#post-124864

**Comment by giucu91** [comment]
Hello @laranz ,

I understand, but if I'll add it like you added it there, all our users who have text logo will also have a tagline after they update and I don't believe this is something they want.

We need to find a solution that leaves the users' website just like it is now and add an option to add tagline in the header. However, this is not so simple because of how the theme was developed.

**Comment by cristianraiber** [comment]
I'm afraid this can be implemented because of the way the theme was initially developed, before we took it over.
