### ISSUE TITLE
[Enchancement] Homepage contents on other pages.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#231]
Many users request this features, they want to replicate the homepage widgets to another pages. Like they want to have a copy of the homepage to other page to have different content. I hope this is not possible, but if you guys find a way, do that.

**Comment by giucu91** [comment]
Hello @laranz ,

I have implemented this, but we will need to make a small documentation for it.
Here are the steps in order to create a page : 

1. Create a new page with the Builder Page template.
2. After you save the page, it will add a sidebar for it. You can go to the Customizer straight from that page and the Sidebar section will be automatically opened. Additionally, you can find the sidebar in Appearance -> Widgets with title : "Page: Page Title".

Hope this make sense, if you need more information please don't hesitate to ask.

Thank you,
George.

**Comment by giucu91** [comment]
Hello @laranz ,

I have implemented this, but we will need to make a small documentation for it.
Here are the steps in order to create a page : 

1. Create a new page with the Builder Page template.
2. After you save the page, it will add a sidebar for it. You can go to the Customizer straight from that page and the Sidebar section will be automatically opened. Additionally, you can find the sidebar in Appearance -> Widgets with title : "Page: Page Title".

Hope this make sense, if you need more information please don't hesitate to ask.

Have a nice day,
George.

**Comment by cristianraiber** [comment]
@laranz - please check this as soon as possible.

**Comment by cristianraiber** [comment]
@laranz - please check this !

**Comment by laranz** [comment]
@cristianraiber tested! Works just fine. 👍
